### ISSUE TITLE
Trim non-critical runtimes

### ISSUE THREAD

**Issue by ericvergnaud** [antlr/antlr5#2]
Since we plan to have only 1 runtime, we should in principle remove all non-Kotlin runtimes.

That said it might be convenient during the initial phase to keep:
 - the Java runtime, as our reference implementation
 - The Typescript runtime, as our first target language, for later conversion to an add-on

**Comment by KvanTTT** [comment]
Currently I don't see big need in trimming at least if it doesn't affect development process (we can do it later). But performance of TypeScript definitely needs to be improved because it negatively affects development experience and remote built: https://github.com/antlr/antlr4/issues/4229

**Comment by ericvergnaud** [comment]
The need is to:
 - have our CI focus on runtimes relevant for ANTLR 5
 - reduce refactoring effort when switching to add-ons

**Comment by KvanTTT** [comment]
Currently it's definitely not possible to get rid of Java runtime because `tool-testsuite` depends on it. Also, Java has some tests that other runtimes don't have (at first they should be ported or removed).

But I'm not sure about current TypeScript runtime. If we are going to use Kotlin for generating WA, I suppose future TypeScript wrapper will have almost nothing in common with the current code. It could increase refactoring effort if keep TypeScript now. Also, TypeScript tests currently are slow (Kotlin tests are also slow but Kotlin is crucial).

**Comment by ericvergnaud** [comment]
Yes the plan is to drop all targets and runtimes except Java (reference runtime and required for the tool), Kotlin, and TypeScript without tests.
We need to keep TypeScript around a bit as a basis for the generated TypeScript parser wrapper (wrapping WebAssembly parser generated from generated Kotlin code, itself linked with the WebAssembly runtime generated from Kotlin).

**Comment by ericvergnaud** [comment]
Fixed with #17
